"""AI Authorship Prediction Service (Module A)

Provides stylometric inference estimating whether phishing text was likely
authored by an LLM vs. written by a human, and exposes cross-generator telemetry.
"""

import json
from pathlib import Path
from typing import Dict, Optional
import joblib
from pydantic import BaseModel, Field
from app.authorship.stylometry import extract_stylometric_features
from app.core.logging import logger

AUTHORSHIP_CAVEAT = "Model-based indicator, not proof of AI authorship."

REPO_DIR = Path(__file__).resolve().parent.parent.parent.parent
if (REPO_DIR / "models" / "authorship").exists():
    MODELS_DIR = REPO_DIR / "models" / "authorship"
else:
    MODELS_DIR = Path(__file__).resolve().parent.parent.parent / "models" / "authorship"


class AuthorshipPredictionResult(BaseModel):
    ai_generated_likelihood: float = Field(..., ge=0.0, le=100.0)
    classification: str
    stylometric_indicators: Dict[str, float] = Field(default_factory=dict)
    caveat: str = AUTHORSHIP_CAVEAT


class AIAuthorshipService:
    """Service wrapping the stylometric random forest classifier and cross-generator metrics."""

    _instance: Optional["AIAuthorshipService"] = None

    def __init__(self, models_dir: Optional[Path] = None):
        self.models_dir = models_dir or MODELS_DIR
        self.classifier = None
        self.scaler = None
        self.metrics: Dict = {}
        self._is_loaded = False
        self.load_artifacts()

    @classmethod
    def get_instance(cls) -> "AIAuthorshipService":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def load_artifacts(self) -> bool:
        """Loads serialized classifier, scaler, and cross-generator metrics."""
        clf_path = self.models_dir / "classifier.joblib"
        scaler_path = self.models_dir / "scaler.joblib"
        metrics_path = self.models_dir / "metrics.json"

        if not (clf_path.exists() and scaler_path.exists()):
            logger.warning("Authorship classifier artifacts not found at %s.", self.models_dir)
            self._is_loaded = False
            return False

        try:
            self.classifier = joblib.load(clf_path)
            self.scaler = joblib.load(scaler_path)

            if metrics_path.exists():
                with open(metrics_path, "r", encoding="utf-8") as f:
                    self.metrics = json.load(f)

            self._is_loaded = True
            logger.info("Successfully loaded AI Authorship classifier and scaler.")
            return True
        except Exception as exc:
            logger.error("Failed to load authorship classifier: %s", exc)
            self._is_loaded = False
            return False

    @property
    def is_ready(self) -> bool:
        return self._is_loaded and self.classifier is not None and self.scaler is not None

    def predict_ai_likelihood(self, text: str) -> AuthorshipPredictionResult:
        """Estimates likelihood (0-100%) that the given text was generated by an LLM."""
        if not text or not text.strip():
            return AuthorshipPredictionResult(
                ai_generated_likelihood=0.0,
                classification="Insufficient Text",
                stylometric_indicators={},
                caveat=AUTHORSHIP_CAVEAT,
            )

        if not self.is_ready:
            # Fallback heuristic estimation
            return AuthorshipPredictionResult(
                ai_generated_likelihood=50.0,
                classification="Uncalibrated",
                stylometric_indicators={},
                caveat=AUTHORSHIP_CAVEAT,
            )

        try:
            vec, feat_dict = extract_stylometric_features(text)
            vec_scaled = self.scaler.transform([vec])
            proba = float(self.classifier.predict_proba(vec_scaled)[0, 1])
            likelihood_pct = round(proba * 100.0, 1)

            classification = "Likely LLM-Generated" if likelihood_pct >= 50.0 else "Likely Human-Written"

            # Filter relevant indicators for presentation
            summary_indicators = {
                "type_token_ratio": feat_dict.get("type_token_ratio", 0.0),
                "sentence_length_mean": feat_dict.get("avg_sentence_length", 0.0),
                "sentence_length_variance": feat_dict.get("sentence_length_variance", 0.0),
                "flesch_reading_ease": feat_dict.get("flesch_reading_ease", 0.0),
                "formal_connective_density": feat_dict.get("formal_connective_density", 0.0),
            }

            return AuthorshipPredictionResult(
                ai_generated_likelihood=likelihood_pct,
                classification=classification,
                stylometric_indicators=summary_indicators,
                caveat=AUTHORSHIP_CAVEAT,
            )
        except Exception as exc:
            logger.error("Error during authorship inference: %s", exc)
            return AuthorshipPredictionResult(
                ai_generated_likelihood=50.0,
                classification="Evaluation Error",
                stylometric_indicators={},
                caveat=AUTHORSHIP_CAVEAT,
            )

    def get_evaluation_metrics(self) -> Dict:
        """Returns in-generator and cross-generator evaluation metrics."""
        return self.metrics


authorship_service = AIAuthorshipService.get_instance()
